export const siteConfig = {
  name: "Bankey Bihari Boxwala",
  shortName: "BBB",
  legalName: "Bankey Bihari Boxwala",
  description:
    "Premium jewellery stock box manufacturer for wholesale buyers across India.",
  url: "https://example.com",
  whatsappNumber: "919999999999",
  whatsappDisplay: "+91 99999 99999",
  email: "sales@bankeybihariboxwala.com",
  location: "Uttar Pradesh, India",
  region: "Uttar Pradesh",
  country: "India",
  pricingNote: "Prices shown are per piece. GST extra.",
  businessHours: "Monday to Saturday · 10:00 AM to 7:00 PM IST",
  serviceArea: "Wholesale enquiries served across India",
  responseTime: "Fast response on WhatsApp for wholesale enquiries",
  orderFlow: [
    "Browse the collection and shortlist relevant products.",
    "Open the product page and review price direction, sizes, colours, and finish.",
    "Start the WhatsApp conversation for quantity, availability, and final discussion.",
    "Continue direct business handling for closing the order smoothly.",
  ],
  trustHighlights: [
    "Wholesale-first order flow",
    "Jewellery-focused catalogue",
    "Premium presentation language",
    "Direct WhatsApp business handling",
    "Clear price direction",
    "India-first trade support",
  ],
  buyerAssurances: [
    "Built for wholesale buyers, not retail confusion",
    "Premium catalogue experience for better first impression",
    "Direct enquiry flow for faster business discussion",
    "Clearer product presentation for easier decision-making",
  ],
  supportTopics: [
    "Bulk quantity discussion",
    "Category selection support",
    "Product availability enquiry",
    "Price clarification",
    "Repeat wholesale ordering",
    "Custom discussion for business buyers",
  ],
};